#!/usr/bin/env bash
# Install the managed SearXNG sidecar into data/searxng/ — no Docker.
# Idempotent: re-running updates the checkout and reuses venv/settings.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOME_DIR="$ROOT/data/searxng"
SRC="$HOME_DIR/src"
VENV="$HOME_DIR/venv"
# NOTE: SEARXNG_PORT only takes effect on first install (settings.yml is not
# overwritten on re-runs). To change the port later: delete
# data/searxng/settings.yml, re-run this script, and update searxng_port in
# Apollo's Settings to match.
PORT="${SEARXNG_PORT:-8893}"

# Validate that PORT is a plain integer.
case "$PORT" in
  (*[!0-9]*|'') echo "ERROR: invalid SEARXNG_PORT value: '$PORT' (must be an integer)"; exit 1;;
esac

# Pinned, not HEAD — same discipline as the Docker image pin. This commit was
# smoke-tested end-to-end (healthz + JSON search) on 2026-06-11. Override with
# SEARXNG_GIT_REF at your own risk.
REF="${SEARXNG_GIT_REF:-4dd0bf48670727f6ae1086ffa72e76f6eb869741}"

mkdir -p "$HOME_DIR"

echo "==> Fetching SearXNG source (pinned: ${REF:0:9})"
if [ ! -d "$SRC/.git" ]; then
  git clone https://github.com/searxng/searxng "$SRC"
fi
# Prefer the local object (offline re-runs); fetch only when it's missing.
# (Fetching a bare SHA requires the server to allow SHA-want fetches —
# GitHub does; a restrictive mirror may not.)
if ! git -C "$SRC" checkout --quiet "$REF" 2>/dev/null; then
  git -C "$SRC" fetch --quiet origin "$REF" --depth 1
  git -C "$SRC" checkout --quiet FETCH_HEAD
fi

echo "==> Creating venv"
if [ ! -x "$VENV/bin/python" ]; then
  python3 -m venv "$VENV"
fi
"$VENV/bin/pip" install -q -U pip setuptools wheel

echo "==> Installing SearXNG dependencies (this can take a few minutes)"
"$VENV/bin/pip" install -q -r "$SRC/requirements.txt"

echo "==> Installing SearXNG"
"$VENV/bin/pip" install -q --use-pep517 --no-build-isolation "$SRC"

if [ ! -f "$HOME_DIR/settings.yml" ]; then
  echo "==> Writing settings.yml"
  SECRET="$("$VENV/bin/python" -c 'import secrets; print(secrets.token_hex(32))')"
  cat > "$HOME_DIR/settings.yml" <<EOF
# Generated by scripts/setup-searxng.sh — localhost-only, JSON API enabled.
use_default_settings: true
server:
  secret_key: "$SECRET"
  bind_address: "127.0.0.1"
  port: $PORT
  limiter: false
  public_instance: false
search:
  formats:
    - html
    - json
EOF
fi

echo "==> Done. Apollo will start the sidecar automatically (searxng_managed=true)."
echo "    Manual start: SEARXNG_SETTINGS_PATH='$HOME_DIR/settings.yml' '$VENV/bin/python' -m searx.webapp"
