#Requires -Version 5.1
<#
  Install the managed SearXNG sidecar into data\searxng\ -- no Docker.
  Idempotent: re-running updates the checkout and reuses venv/settings.

  Usage:
    powershell -NoProfile -ExecutionPolicy Bypass -File .\scripts\setup-searxng.ps1

  NOTE: SEARXNG_PORT only takes effect on first install (settings.yml is not
  overwritten on re-runs). To change the port later: delete
  data\searxng\settings.yml, re-run this script, and update searxng_port in
  Apollo's Settings to match.
#>

$ErrorActionPreference = 'Stop'

$ROOT     = Split-Path -Parent $PSScriptRoot
$HOME_DIR = Join-Path $ROOT "data\searxng"
$SRC      = Join-Path $HOME_DIR "src"
$VENV     = Join-Path $HOME_DIR "venv"
$PORT     = if ($env:SEARXNG_PORT) { $env:SEARXNG_PORT } else { "8893" }

function Write-Step($msg) { Write-Host ("==> " + $msg) }
function Fail($msg) {
    Write-Host ("ERROR: " + $msg)
    exit 1
}

# Validate that PORT is a plain integer.
$portInt = 0
if (-not [int]::TryParse($PORT, [ref]$portInt)) {
    Fail "invalid SEARXNG_PORT value: '$PORT' (must be an integer)"
}

# Pinned, not HEAD -- same discipline as the Docker image pin. This commit was
# smoke-tested end-to-end (healthz + JSON search) on 2026-06-11. Override with
# SEARXNG_GIT_REF at your own risk.
$REF = if ($env:SEARXNG_GIT_REF) { $env:SEARXNG_GIT_REF } else { "4dd0bf48670727f6ae1086ffa72e76f6eb869741" }

# Create data directory
if (-not (Test-Path $HOME_DIR)) {
    New-Item -ItemType Directory -Path $HOME_DIR | Out-Null
}

# --- Fetch SearXNG source ---
Write-Step ("Fetching SearXNG source (pinned: " + $REF.Substring(0, 9) + ")")
$gitDir = Join-Path $SRC ".git"
if (-not (Test-Path $gitDir)) {
    git clone https://github.com/searxng/searxng $SRC
    if ($LASTEXITCODE -ne 0) { Fail "git clone failed." }
}
$prevLoc = Get-Location
Set-Location $SRC
# Prefer the local object (offline re-runs); fetch only when it's missing.
git checkout --quiet $REF 2>$null
if ($LASTEXITCODE -ne 0) {
    git fetch --quiet origin $REF --depth 1
    if ($LASTEXITCODE -ne 0) { Set-Location $prevLoc; Fail "git fetch of pinned ref failed." }
    git checkout --quiet FETCH_HEAD
    if ($LASTEXITCODE -ne 0) { Set-Location $prevLoc; Fail "git checkout of pinned ref failed." }
}
Set-Location $prevLoc

# --- Locate a suitable Python interpreter ---
Write-Step "Creating venv"

$venvPy = Join-Path $VENV "Scripts\python.exe"
if (-not (Test-Path $venvPy)) {
    $pyExe  = $null
    $pyArgs = @()

    $pyLauncher = Get-Command py -ErrorAction SilentlyContinue
    if ($pyLauncher) {
        foreach ($v in @("-3.13", "-3.12", "-3.11", "-3.10", "-3")) {
            try {
                $ver = (& $pyLauncher.Source $v -c "import sys; print(sys.version_info[0])" 2>$null).Trim()
                if ($ver -eq "3") {
                    $pyExe  = $pyLauncher.Source
                    $pyArgs = @($v)
                    break
                }
            } catch { }
        }
    }

    if (-not $pyExe) {
        $pythonCmd = Get-Command python -ErrorAction SilentlyContinue
        if ($pythonCmd) {
            $pyExe = $pythonCmd.Source
        }
    }

    if (-not $pyExe) {
        Fail "Python 3 not found. Install Python 3.10+ from https://www.python.org/downloads/ and re-run."
    }

    & $pyExe @pyArgs -m venv $VENV
    if ($LASTEXITCODE -ne 0) { Fail "Failed to create virtual environment." }
    if (-not (Test-Path $venvPy)) { Fail "venv was created but python.exe not found at expected path." }
}

# --- Upgrade pip / setuptools / wheel ---
& $venvPy -m pip install -q -U pip setuptools wheel
if ($LASTEXITCODE -ne 0) { Fail "pip upgrade failed." }

# --- Install SearXNG dependencies ---
Write-Step "Installing SearXNG dependencies (this can take a few minutes)"
$reqFile = Join-Path $SRC "requirements.txt"
& $venvPy -m pip install -q -r $reqFile
if ($LASTEXITCODE -ne 0) { Fail "Dependency install failed." }

# --- Install SearXNG package ---
Write-Step "Installing SearXNG"
& $venvPy -m pip install -q --use-pep517 --no-build-isolation $SRC
if ($LASTEXITCODE -ne 0) { Fail "SearXNG package install failed." }

# --- Write settings.yml (only on first install) ---
$settingsFile = Join-Path $HOME_DIR "settings.yml"
if (-not (Test-Path $settingsFile)) {
    Write-Step "Writing settings.yml"
    $SECRET = (& $venvPy -c "import secrets; print(secrets.token_hex(32))").Trim()
    if ($LASTEXITCODE -ne 0) { Fail "Failed to generate secret key." }
    $yaml = @"
# Generated by scripts/setup-searxng.ps1 -- localhost-only, JSON API enabled.
use_default_settings: true
server:
  secret_key: "$SECRET"
  bind_address: "127.0.0.1"
  port: $PORT
  limiter: false
  public_instance: false
search:
  formats:
    - html
    - json
"@
    [System.IO.File]::WriteAllText($settingsFile, $yaml, [System.Text.Encoding]::UTF8)
}

Write-Step "Done. Apollo will start the sidecar automatically (searxng_managed=true)."
Write-Host ("    Manual start: set SEARXNG_SETTINGS_PATH=" + $settingsFile + " & " + $venvPy + " -m searx.webapp")
